#! /usr/bin/env python
import sys
import requests

url = sys.argv[1]

payload = { 'firstname' : 'value', 'lastname' : 'value2' }
files = { 'lastname' : 'bar' }
r = requests.post(url, data=payload)

#r2 = requests.post(url, data=payload, files=files)

print r.status_code
#print r.text

#print r2.status_code

